import Foundation

/// Compatibility metadata for saved menu titles, not text to display or persist.
/// The table is derived from the existing Base menu, never from user menus.
@objc(iTermMenuItemLegacyTitles)
final class MenuItemLegacyTitles: NSObject {
    private static let aliases: [(identifier: String?, titles: Set<String>)] = {
        let bundles = Bundle.main.localizations.filter { $0 != "Base" }.compactMap { locale in
            Bundle.main.path(forResource: locale, ofType: "lproj").flatMap(Bundle.init(path:))
        }
        return entries.map { entry in
            var titles: Set<String> = [entry.title]
            for bundle in bundles {
                titles.insert(bundle.localizedString(forKey: entry.key, value: entry.title, table: "MainMenu"))
            }
            return (entry.identifier, titles)
        }
    }()

    @objc(matchesTitle:identifier:currentTitle:)
    static func matches(title: String, identifier: String?, currentTitle: String) -> Bool {
        guard !title.isEmpty,
              Bundle.main.object(forInfoDictionaryKey: "iTermCNCommunityBuild") as? Bool == true else {
            return false
        }
        return aliases.contains { entry in
            if let identifier = identifier {
                return entry.identifier == identifier && entry.titles.contains(title)
            }
            return entry.identifier == nil && entry.titles.contains(title) && entry.titles.contains(currentTitle)
        }
    }

    // BEGIN GENERATED MENU TITLES
    private static let entries: [(key: String, identifier: String?, title: String)] = [
        ("56.title", nil, "iTerm2"),
        ("233.title", "About iTerm2", "About iTerm2"),
        ("ft3-BP-igZ.title", "Show Tip of the Day", "Show Tip of the Day"),
        ("Cmp-n0-De1.title", "Pair Companion Device", "Companion Device Settings"),
        ("SuA-lr-t01.title", "Suppressed Alerts", "Suppressed Alerts…"),
        ("880.title", "Check For Updates…", "Check for Updates…"),
        ("950.title", "Toggle Debug Logging", "Toggle Debug Logging"),
        ("Rtr-Sv-Log.title", "Save Retrospective Debug Logs", "Save Retrospective Debug Logs"),
        ("cYu-lQ-5GD.title", "Copy Performance Stats", "Copy Performance Stats"),
        ("8KO-hG-xdC.title", "Capture Metal Frame", "Capture GPU Frame"),
        ("129.title", "Preferences...", "Preferences..."),
        ("131.title", nil, "Services"),
        ("134.title", "Hide iTerm2", "Hide iTerm2"),
        ("145.title", "Hide Others", "Hide Others"),
        ("150.title", "Show All", "Show All"),
        ("1174.title", "Secure Keyboard Entry", "Secure Keyboard Entry"),
        ("1470.title", "Make iTerm2 Default Term", "Make iTerm2 Default Term"),
        ("1473.title", "Make Terminal Default Term", "Make Terminal Default Term"),
        ("rHN-nq-xah.title", "Install Shell Integration", "Install Shell Integration"),
        ("Qef-e2-NCc.title", "Install Claude Code Integration", "Install Claude Code Integration"),
        ("Req-e2-NCc.title", "Reinstall Claude Code Integration", "Reinstall Claude Code Integration"),
        ("O3D-kK-x3j.title", "Uninstall Claude Code Integration", "Uninstall Claude Code Integration"),
        ("WcV-7l-ycc.title", "Remove Recent Profiles from Dock Menu", "Remove Recent Profiles from Dock Menu"),
        ("136.title", "Quit iTerm2", "Quit iTerm2"),
        ("83.title", nil, "Shell"),
        ("872.title", "New Window", "New Window"),
        ("LR1-f6-Fa9.title", "New Window with Current Profile", "New Window with Current Profile"),
        ("867.title", "New Tab", "New Tab"),
        ("YXw-k6-LJh.title", "New Tab Next to Current Tab", "New Tab Next to Current Tab"),
        ("1302.title", "New Tab with Current Profile", "New Tab with Current Profile"),
        ("9BQ-Nt-1uD.title", "Duplicate Window", "Duplicate Window"),
        ("Heo-Xb-RKN.title", "Duplicate Tab", "Duplicate Tab"),
        ("1201.title", "Split Horizontally with Current Profile", "Split Horizontally with Current Profile"),
        ("1200.title", "Split Vertically with Current Profile", "Split Vertically with Current Profile"),
        ("1289.title", "Split Horizontally…", "Split Horizontally…"),
        ("1291.title", "Split Vertically…", "Split Vertically…"),
        ("eia-2d-pmU.title", "Log.SaveContents", "Save Contents…"),
        ("692.title", "Save Selected Text…", "Save Selected Text…"),
        ("1184.title", "Close", "Close"),
        ("598.title", "Close Terminal Window", "Close Terminal Window"),
        ("635.title", "Close All Panes in Tab", "Close All Panes in Tab"),
        ("OIr-XE-oT1.title", "Undo Close", "Undo Close"),
        ("fb0-0W-qYG.title", nil, "Archives"),
        ("owl-7s-n9a.title", "saveArchive:", "Save Archive of Current Session…"),
        ("UXA-3l-Mrb.title", "restoreArchive:", "Restore Archive…"),
        ("OW4-ru-6dZ.title", nil, "Workgroups"),
        ("JqP-Wg-vG9.title", "Exit Workgroup", "Exit Workgroup"),
        ("1261.title", nil, "Broadcast Input"),
        ("1268.title", "Broadcast Input.Send Input to Current Session Only", "Send Input to Current Session Only"),
        ("1264.title", "Broadcast Input.Broadcast Input to All Panes in All Tabs", "Broadcast Input to All Panes in All Tabs"),
        ("1266.title", "Broadcast Input.Broadcast Input to All Panes in Current Tab", "Broadcast Input to All Panes in Current Tab"),
        ("1477.title", "Broadcast Input.Toggle Broadcast Input to Current Session", "Toggle Broadcast Input to Current Session"),
        ("1412.title", "Broadcast Input.Show Background Pattern Indicator", "Show Background Pattern Indicator"),
        ("QhX-mz-L6a.title", "Broadcast Input.Current Session is Broadcast Source", "Current Session is Broadcast Source"),
        ("Irq-lZ-Iy6.title", "Toggle Buffer Input", "Toggle Buffer Input"),
        ("1448.title", nil, "tmux"),
        ("1459.title", "tmux.Detach", "Detach"),
        ("BV1-u8-JSz.title", "tmux.Force Detach", "Force Detach"),
        ("1455.title", "tmux.New Tmux Window", "New Tmux Window"),
        ("1452.title", "tmux.New Tmux Tab", "New Tmux Tab"),
        ("Rtn-t8-0OH.title", "trmux.Pause Pane", "Pause Pane"),
        ("1461.title", "tmux.Dashboard", "Dashboard"),
        ("NGU-fy-0o1.title", nil, "ssh"),
        ("ycJ-VX-uQI.title", "ssh.Disconnect", "Disconnect"),
        ("TeM-om-H0z.title", "ssh.Download Files", "Download Files…"),
        ("it2-au-th0.title", "ssh.Remote host can control iTerm2", "Remote host can control iTerm2"),
        ("685.title", "Page Setup...", "Page Setup..."),
        ("822.title", nil, "Print"),
        ("823.title", "Print.Screen", "Screen"),
        ("825.title", "Print.Selection", "Selection"),
        ("826.title", "Print.Buffer", "Buffer"),
        ("163.title", nil, "Edit"),
        ("1061.title", "Undo", "Undo"),
        ("1063.title", "Redo", "Redo"),
        ("157.title", "Cut", "Cut"),
        ("1326.title", "Copy", "Copy"),
        ("n4U-yI-y7D.title", "Copy with Styles", "Copy with Styles"),
        ("GT8-oj-uFO.title", "Copy with Control Sequences", "Copy with Control Sequences"),
        ("CQc-0U-rfn.title", "Copy Mode", "Copy Mode"),
        ("213.title", "Paste", "Paste"),
        ("1158.title", nil, "Paste Special"),
        ("tnr-HI-5ah.title", "Paste Special.Advanced Paste…", "Advanced Paste…"),
        ("1164.title", "Paste Special.Paste Selection", "Paste Selection"),
        ("Xn8-na-Zys.title", "Paste Special.Paste File Base64-Encoded", "Paste File Base64-Encoded"),
        ("1166.title", "Paste Special.Paste Slowly", "Paste Slowly"),
        ("1483.title", "Paste Special.Paste Faster", "Paste Faster"),
        ("1492.title", "Paste Special.Paste Slowly Faster", "Paste Slowly Faster"),
        ("1489.title", "Paste Special.Paste Slower", "Paste Slower"),
        ("1494.title", "Paste Special.Paste Slowly Slower", "Paste Slowly Slower"),
        ("IH2-H8-9Ao.title", "Paste Special.Warn Before Multi-Line Paste", "Warn Before Multi-Line Paste"),
        ("L16-T3-OVz.title", "Paste Special.Limit Multi-Line Paste Warning to Shell Prompt", "Limit Multi-Line Paste Warning to Shell Prompt"),
        ("GqP-hQ-yD1.title", "Paste Special.Prompt to Convert Tabs to Spaces when Pasting", "Prompt to Convert Tabs to Spaces when Pasting"),
        ("YHP-Qx-eCZ.title", "Paste Special.Warn Before Pasting One Line Ending in a Newline at Shell Prompt", "Warn Before Pasting One Line Ending in a Newline at Shell Prompt"),
        ("5uf-4h-Tfe.title", nil, "Replace Selection"),
        ("SEy-mc-25m.title", "Render Selection Natively", "Render Selection Natively"),
        ("Fsl-eD-Noh.title", "Replace Selection.Replace with Pretty-Printed JSON", "Replace with Pretty-Printed JSON"),
        ("ZaV-ga-7GF.title", "Replace Selection.Replace with Base 64-Encoded Value", "Replace with Base 64-Encoded Value"),
        ("3Es-XB-YYS.title", "Replace Selection.Replace with Base 64-Decoded Value", "Replace with Base 64-Decoded Value"),
        ("zgu-Gv-WUr.title", "Engage Artificial Intelligence", "Engage Artificial Intelligence"),
        ("vlr-uw-Err.title", "Explain Output with AI", "Explain Output with AI"),
        ("s0f-jP-7Pk.title", "Edit.Snippets", "Snippets"),
        ("8Ja-GB-Waf.title", "Edit.Actions", "Actions"),
        ("upW-1r-eM7.title", "Open Selection", "Open Selection"),
        ("764.title", "Find.Jump to Selection", "Jump to Selection"),
        ("172.title", "Select All", "Select All"),
        ("jDU-f2-OSh.title", "Selection Respects Soft Boundaries", "Selection Respects Soft Boundaries"),
        ("JqU-xR-XbI.title", "Select Output of Last Command", "Select Output of Last Command"),
        ("SCG-gK-0nY.title", "Select Current Command", "Select Current Command"),
        ("759.title", nil, "Find"),
        ("Bx1-Fd-J2S.title", "Find.Find...", "Find…"),
        ("761.title", "Find.Find Next", "Find Next"),
        ("763.title", "Find.Find Previous", "Find Previous"),
        ("758.title", "Find.Use Selection for Find", "Use Selection for Find"),
        ("VDU-gj-HpO.title", "Find.Clear Find", "Clear Find"),
        ("yIL-PC-jnC.title", "Find.Find Globally...", "Find Globally..."),
        ("ULH-1B-QtL.title", "Find.ConvertMatchesToSelections", "Select Matches"),
        ("VPn-YM-CGp.title", "Find.Find URLs", "Find URLs"),
        ("MFq-yU-N9S.title", "Find.Find All Smart Selection  Matches", "Find All Smart Selection Matches"),
        ("KTc-zQ-Rb6.title", "Find.Pick Result To Open", "Pick Result to Open"),
        ("rPD-q2-ZI6.title", "Find.Filter", "Filter"),
        ("Lfh-pN-XLJ.title", nil, "Marks and Annotations"),
        ("1243.title", "Marks and Annotations.Set Mark", "Set Mark"),
        ("1245.title", "Marks and Annotations.Jump to Mark", "Jump to Mark"),
        ("mcu-LX-9Aj.title", "Marks and Annotations.Next Mark", "Next Mark"),
        ("sZa-7I-YDa.title", "Marks and Annotations.Previous Mark", "Previous Mark"),
        ("Fna-Ng-9y6.title", "Marks and Annotations.Add Annotation at Cursor", "Add Annotation at Cursor"),
        ("aNs-El-c10.title", "Marks and Annotations.Annotate Selection", "Annotate Selection"),
        ("FvD-eZ-yBV.title", "Marks and Annotations.Next  Annotation", "Next Annotation"),
        ("q2T-zq-icd.title", "Marks and Annotations.Previous  Annotation", "Previous Annotation"),
        ("noE-Gg-Cgs.title", nil, "Alerts"),
        ("Qj6-xH-l9X.title", "Marks and Annotations.Alerts.Alert on Next Mark", "Alert on Next Mark"),
        ("qcQ-i5-i8s.title", "Marks and Alerts.Alerts.Alert on Marks in Offscreen Sessions", "Alert on Marks in Offscreen Sessions"),
        ("mat-0d-WzN.title", "Marks and Annotations.Alerts.Show Modal Alert Box", "Show Modal Alert Box"),
        ("QeX-5T-qxA.title", "Marks and Annotations.Alerts.Post Notification", "Post Notification"),
        ("Mhn-ha-kyp.title", "Marks and Notes.Alerts.Play a Sound", "Play a Sound"),
        ("8d7-qE-wpn.title", "Set Named Mark", "Set Named Mark"),
        ("bWZ-Rb-J4D.title", nil, "Named Marks"),
        ("1242.title", nil, "Item 1"),
        ("1241.title", nil, "Item 2"),
        ("1240.title", nil, "Item 3"),
        ("7ly-zH-p8X.title", "Fold Selected Lines", "Fold Selected Lines"),
        ("fAC-xy-123.title", "Fold All Above Cursor", "Fold All"),
        ("5EJ-KF-6Ll.title", nil, "Item 1"),
        ("Laq-Gc-l1k.title", nil, "Item 2"),
        ("pqa-Lr-NlO.title", nil, "Item 3"),
        ("217.title", "Clear Buffer", "Clear Buffer"),
        ("dxF-XL-vIa.title", "Clear Instant Replay", "Clear Instant Replay"),
        ("755.title", "Clear Scrollback Buffer", "Clear Scrollback Buffer"),
        ("CYE-nw-eWv.title", "Clear to Start of Selection", "Clear to Start of Selection"),
        ("Xsz-J9-7ar.title", "Clear to Last Mark", "Clear to Last Mark"),
        ("802.title", nil, "View"),
        ("1257.title", "Show Tabs in Fullscreen", "Show Tabs in Fullscreen"),
        ("914.title", "Toggle Full Screen", "Toggle Full Screen"),
        ("1295.title", "Toolbelt", "Toolbelt"),
        ("1297.title", "Show Toolbelt", "Show Toolbelt"),
        ("81r-Vc-nVm.title", "Set Default Width", "Set Default Width"),
        ("1228.title", "Use Transparency", "Use Transparency"),
        ("FNR-IX-80x.title", "Disable Transparency for Active Window", "Disable Transparency for Active Window"),
        ("Atu-fG-56G.title", "Zoom In on Selection", "Zoom In on Selection"),
        ("0A4-80-ghh.title", "Zoom Out", "Zoom Out"),
        ("1286.title", "Find Cursor", "Find Cursor"),
        ("pAu-j3-wEC.title", "Show Annotations", "Show Annotations"),
        ("Clp-vw-ShC.title", "Show Clippings", "Show Clippings"),
        ("InC-vw-ShC.title", "Show Inline Chat", "Show Inline Chat"),
        ("Bhs-45-5yR.title", "Composer", "Show Composer"),
        ("DcF-ub-g6d.title", "Show Cursor Guide", "Show Cursor Guide"),
        ("sNt-vw-E1q.title", "Edit Session Note", "Show Session Note"),
        ("TnF-kz-Lf0.title", "Show Timestamps", "Show Timestamps"),
        ("9DF-nf-qif.title", "Auto Command Completion", "Auto Command Completion"),
        ("TJi-5Q-RCM.title", "Auto Composer", "Auto Composer"),
        ("Knm-gZ-dFc.title", "Open Quickly", "Open Quickly"),
        ("1233.title", "Maximize Active Pane", "Maximize Active Pane"),
        ("804.title", "Make Text Bigger", "Make Text Bigger"),
        ("1464.title", "Make Text Normal Size", "Make Text Normal Size"),
        ("1467.title", "Restore Text and Session Size", "Restore Text and Session Size"),
        ("805.title", "Make Text Smaller", "Make Text Smaller"),
        ("wau-MD-nUH.title", "Size Changes Update Profile", "Size Changes Update Profile"),
        ("976.title", "Start Instant Replay", "Start Instant Replay"),
        ("ZGW-Bo-6S6.title", "Session", "Session"),
        ("954.title", "Edit Session…", "Edit Session…"),
        ("1305.title", "Run Coprocess…", "Run Coprocess…"),
        ("1321.title", "Stop Coprocess", "Stop Coprocess"),
        ("Jvo-Bw-UNg.title", "Restart Session", "Restart Session"),
        ("01D-vQ-sLv.title", "Duplicate Session", "Duplicate Session"),
        ("1144.title", "Open Autocomplete…", "Open Autocomplete…"),
        ("MXE-be-qxv.title", "Open Command History…", "Open Command History…"),
        ("7X6-Am-EEB.title", "Open Recent Directories…", "Open Recent Directories…"),
        ("1142.title", "Open Paste History…", "Open Paste History…"),
        ("tkq-fN-kF5.title", "Open AI Chat", "Open AI Chat…"),
        ("DB9-tf-hPg.title", "Triggers", "Triggers"),
        ("xcL-dd-3m4.title", "Add Trigger", "Add Trigger…"),
        ("rRB-v6-pdW.title", "Edit Triggers", "Edit Triggers"),
        ("lA4-rW-ioh.title", "Enable Triggers in Interactive Apps", "Enable Triggers in Interactive Apps"),
        ("mcR-jM-n5n.title", "Triggers.Enable All", "Enable All"),
        ("B3C-jO-rIU.title", "Triggers.Disable All", "Disable All"),
        ("907.title", "Reset", "Reset"),
        ("1500.title", "Reset Character Set", "Reset Character Set"),
        ("B8N-yx-8Zh.title", nil, "Move Session"),
        ("Hlz-4M-IYw.title", "Move Session to Window", "Move Session to Window"),
        ("GfE-qn-Fur.title", "Move Session to Tab", "Move Session to Tab"),
        ("3uK-At-K7k.title", "Move Session to Split Pane", "Move Session to Split Pane"),
        ("227.title", nil, "Log"),
        ("dj8-Cg-b5y.title", "Log.Toggle", "Log to File"),
        ("Xu9-L5-uPr.title", "Log.ImportRecording", "Import Recording"),
        ("Bxx-ai-xsx.title", "Log.ExportRecording", "Export Recording"),
        ("scr-Ob-001.title", "Make Screenshot", "Make Screenshot…"),
        ("oeT-w1-6UG.title", nil, "Terminal State"),
        ("n7j-J8-y3V.title", "Alternate Screen", "Alternate Screen"),
        ("2Ek-PE-o7F.title", "Focus Reporting", "Focus Reporting"),
        ("Lbh-lI-2tO.title", "Mouse Reporting", "Mouse Reporting"),
        ("FNV-7O-Feh.title", "Paste Bracketing", "Paste Bracketing"),
        ("6d3-xQ-NPR.title", "Application Cursor", "Application Cursor"),
        ("xWN-I8-ExG.title", "Application Keypad", "Application Keypad"),
        ("NiW-ZC-qkW.title", "Terminal State.Standard Key Reporting", "Standard Key Reporting Mode"),
        ("xK3-pO-8bT.title", "Terminal State.Report Modifiers like xterm 1", "modifyOtherKeys Mode 1"),
        ("kN6-Ru-Vvk.title", "Terminal State.Report Modifiers like xterm 2", "modifyOtherKeys Mode 2"),
        ("Qlm-EZ-J8K.title", "Terminal State.Report Modifiers with CSI u", "CSI u Mode"),
        ("HUg-bw-Kax.title", "Terminal State.Raw Key Reporting", "Raw Key Reporting Mode"),
        ("KSe-b9-e6z.title", "Terminal State.Disambiguate Escape", "Disambiguate Escape"),
        ("xAJ-2s-wRO.title", "Terminal State.Report All Event Types", "Report All Event Types"),
        ("OeA-3R-GMn.title", "Terminal State.Report Alternate Keys", "Report Alternate Keys"),
        ("Hnr-VA-NP8.title", "Terminal State.Report All Keys as Escape Codes", "Report All Keys as Escape Codes"),
        ("dP6-Qg-oWM.title", "Terminal State.Report Associated Text", "Report Associated Text"),
        ("vdB-Qh-wxH.title", "Terminal State.Literal Mode", "Literal Controls"),
        ("uco-jF-Gq5.title", nil, "Emulation Level"),
        ("Xze-0w-34U.title", "Terminal State.Emulation Level.VT100", "VT100"),
        ("Yat-BG-Cr5.title", "Terminal State.Emulation Level.VT200", "VT200"),
        ("P4S-PI-zKU.title", "Terminal State.Emulation Level.VT300", "VT300"),
        ("AfM-Tg-ZYT.title", "Terminal State.Emulation Level.VT400", "VT400"),
        ("CLa-er-Pr0.title", "Terminal State.Emulation Level.VT500", "VT500"),
        ("Hb6-C9-aDf.title", "Reset Terminal State", "Reset"),
        ("m8k-FC-JBb.title", "Bury Session", "Bury Session"),
        ("Weo-nd-iLL.title", nil, "Buried Sessions"),
        ("eAB-5s-fVh.title", nil, "Scripts"),
        ("Koa-MY-5QA.title", nil, "Manage"),
        ("ds5-gY-cX0.title", "New Python Script", "New Python Script"),
        ("jXH-0I-Wtc.title", "Open Interactive Window", "Open Python REPL"),
        ("wHh-8e-oU2.title", "Manage Dependencies", "Manage Dependencies…"),
        ("0D0-tt-wlA.title", "Install Python Runtime", "Install Python Runtime"),
        ("t3w-Wj-vG8.title", "Install Already-Downloaded Python Runtime", "Install Already-Downloaded Python Runtime"),
        ("eeH-ly-45H.title", "Reveal in Finder", "Reveal Scripts in Finder"),
        ("hZE-iO-QIR.title", "Import Script", "Import…"),
        ("dlj-rW-u7D.title", "Export Script", "Export…"),
        ("YqT-f8-W2j.title", "Script Console", "Console"),
        ("591.title", ".Profiles", "Profiles"),
        ("952.title", "Open Profiles…", "Open Profiles…"),
        ("875.title", "Press Option for New Window", "Press Option for New Window"),
        ("878.title", "Open In New Window", "Open In New Window"),
        ("19.title", nil, "Window"),
        ("23.title", "Minimize", "Minimize"),
        ("882.title", "Zoom", "Zoom"),
        ("OBk-Hd-j3M.title", "Arrangements", "Arrangements"),
        ("1205.title", "Save Window Arrangement", "Save Window Arrangement"),
        ("D5Y-FD-IWK.title", "Save Current Window as Arrangement", "Save Current Window as Arrangement"),
        ("wNF-TH-Fz5.title", "Load Arrangement from File…", "Load Arrangement from File…"),
        ("1280.title", nil, "Restore Window Arrangement"),
        ("z6V-EJ-Ntf.title", nil, "Restore Window Arrangement as Tabs"),
        ("58Y-0j-mff.title", "Change Profile in Arrangement…", "Change Profile in Arrangement…"),
        ("STe-pB-R3v.title", "Edit Window Title", "Edit Window Title"),
        ("Tel-UC-zi5.title", nil, "Tab"),
        ("o4x-qQ-aC9.title", "Edit Tab Title", "Edit Tab Title"),
        ("847.title", nil, "Select Tab"),
        ("845.title", "Select Next Tab", "Select Next Tab"),
        ("843.title", "Select Previous Tab", "Select Previous Tab"),
        ("nTg-01-nxt.title", "Select Next Tab Group", "Select Next Tab Group"),
        ("pTg-01-prv.title", "Select Previous Tab Group", "Select Previous Tab Group"),
        ("1QV-xl-Oun.title", nil, "Move Tab"),
        ("1406.title", "Move Tab to New Window", "Move Tab to New Window"),
        ("Tf4-UH-zAS.title", "Move Tab Left", "Move Tab Left"),
        ("1408.title", "Move Tab Right", "Move Tab Right"),
        ("tgA-01-new.title", "Add Tab to New Group", "Add Tab to New Group…"),
        ("tgR-01-rem.title", "Remove Tab from Group", "Remove Tab from Group"),
        ("wXP-h9-8lp.title", nil, "Split Pane"),
        ("1209.title", nil, "Select Split Pane"),
        ("1212.title", "Select Split Pane.Select Pane Above", "Select Pane Above"),
        ("1213.title", "Select Split Pane.Select Pane Below", "Select Pane Below"),
        ("1214.title", "Select Split Pane.Select Pane Left", "Select Pane Left"),
        ("1215.title", "Select Split Pane.Select Pane Right", "Select Pane Right"),
        ("1250.title", "Select Split Pane.Next Pane", "Next Pane"),
        ("1251.title", "Select Split Pane.Previous Pane", "Previous Pane"),
        ("OCq-v2-LJk.title", "Select Split Pane.Previous Peer", "Previous Peer"),
        ("ZtC-pi-TV2.title", "Select Split Pane.Next Peer", "Next Peer"),
        ("R0v-Kn-z9m.title", nil, "Resize Split Pane"),
        ("2Jk-GR-zCt.title", "Resize Split Pane.Move Divider Up", "Move Divider Up"),
        ("Qpv-Ie-1sh.title", "Resize Split Pane.Move Divider Down", "Move Divider Down"),
        ("avG-JI-rjO.title", "Resize Split Pane.Move Divider Left", "Move Divider Left"),
        ("t6w-8j-r4m.title", "Resize Split Pane.Move Divider Right", "Move Divider Right"),
        ("OsT-y6-DSn.title", "Lock Split Pane Width", "Lock Split Pane Width"),
        ("Va7-Bb-mhX.title", nil, "Window Style"),
        ("2GY-cf-R3u.title", "Window Style.Normal", "Normal"),
        ("7YH-d7-iVT.title", "Window Style.Full Screen", "Full Screen"),
        ("yOg-Xf-9Ja.title", "Window Style.Maximized", "Maximized"),
        ("c9F-P9-dcr.title", "Window Style.No Title Bar", "No Title Bar"),
        ("5lc-iD-Td3.title", "Window Style.Centered", "Centered"),
        ("VcO-5C-gYt.title", "Window Style.FullWidth Bottom of Screen", "Full-Width Bottom of Screen"),
        ("xx4-Ao-jke.title", "Window Style.FullWidth Top of Screen", "Full-Width Top of Screen"),
        ("8Up-pV-Ad7.title", "Window Style..FullHeight Left of Screen", "Full-Height Left of Screen"),
        ("Nbx-zl-DQO.title", "Window Style.FullHeight Right of Screen", "Full-Height Right of Screen"),
        ("GpQ-q3-0fg.title", "Window Style.Bottom of Screen", "Bottom of Screen"),
        ("K5f-FR-QxY.title", "Window Style.Top of Screen", "Top of Screen"),
        ("5VM-vY-8EI.title", "Window Style.Left of Screen", "Left of Screen"),
        ("Xma-aq-b5U.title", "Window Style.Right of Screen", "Right of Screen"),
        ("df3-h4-b4O.title", "Lock Size", "Lock Size"),
        ("Lk1-Ly-Lt0.title", "Lock Layout", "Lock Layout"),
        ("Ns0-Ch-G01.title", "Notify on Status Change", "Notify on Status Change"),
        ("tt8-Pq-lBv.title", nil, "Arrange Windows"),
        ("Kb8-2V-7Gg.title", "Merge All Windows", "Merge All Windows"),
        ("1178.title", "Arrange Windows Horizontally", "Arrange Windows Horizontally"),
        ("xtk-nu-uNt.title", "Arrange Split Panes Evenly", "Arrange Split Panes Evenly"),
        ("X81-5E-VA5.title", nil, "Resize Window"),
        ("E89-Mw-yOH.title", "Resize Window.Decrease Height", "Decrease Height"),
        ("1L5-Nc-laa.title", "Resize Window.Increase Height", "Increase Height"),
        ("XkO-DN-h6r.title", "Resize Window.Decrease Width", "Decrease Width"),
        ("ql8-uk-qRc.title", "Resize Window.Increase Width", "Increase Width"),
        ("5.title", "Password Manager", "Password Manager"),
        ("okQ-cw-xCt.title", "AI Chats", "AI Chats"),
        ("g30-gR-6hU.title", "Cockpit", "Cockpit"),
        ("Kd2-6A-mAn.title", "Pin Hotkey Window", "Pin Hotkey Window"),
        ("f7R-Y0-F8w.title", "Bring All To Front", "Bring All To Front"),
        ("103.title", nil, "Help"),
        ("111.title", "iTerm2 Help", "iTerm2 Help"),
        ("wTB-km-9Qm.title", "Copy Mode Shortcuts", "Copy Mode Shortcuts"),
        ("dV2-dF-UB1.title", "Open Source Licenses", "Open Source Licenses"),
        ("16n-FV-p0f.title", "GPU Renderer Availability", "GPU Renderer Availability"),
        ("vvf-qA-Pf7.title", "replaceSelectionWithPrettyPrintedJSON:", "Replace with Pretty-Printed JSON"),
        ("7NG-s1-th2.title", nil, "Item"),
        ("Dn5-OV-QtF.title", "Web", "Web"),
        ("1jY-S7-DWS.title", "browserOpenLocation:", "Open Location…"),
        ("WKv-50-M5a.title", "browserBack:", "Back"),
        ("Osn-cN-dXN.title", "browserForward:", "Forward"),
        ("hJc-IO-faA.title", "browserReload:", "Reload Page"),
        ("uSW-pP-LFB.title", "browserHistory:", "History"),
    ]
    // END GENERATED MENU TITLES
}
